# Generated by Django 3.0 on 2021-02-25 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210222_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post'),
            preserve_default=False,
        ),
    ]
