# Generated by Django 3.0 on 2021-03-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name=['%I:%H %p']),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name=['%d-%m-%Y']),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='post'),
        ),
    ]
