# Generated by Django 3.0.10 on 2021-03-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210307_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='id_user',
            new_name='autor',
        ),
    ]
