# Generated by Django 3.0 on 2021-03-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210301_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name=[]),
        ),
    ]
